spring:
  application:
    name: message-api
#  cloud:
#    config:
#      enabled: false
server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
message: This message is from default configuration

